apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name     : {{ .Values.general.name }}-ingress
  namespace: {{ .Values.general.namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 5 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.paths.authn.path }}
            pathType: {{ .Values.ingress.paths.authn.pathType }}
            backend:
              service:
                name: {{ .Values.general.name }}-svc
                port:
                  number: {{ .Values.ingress.paths.authn.service_port }}
    # tls:
  #   - hosts:
  #     - {{ .Values.ingress.host }}
  #     secretName: {{ .Values.ingress.secretCertName }}
