{{- if .Values.serviceaccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.general.name }}-service-account
  namespace: {{ .Release.Namespace }}
  {{- with .Values.general.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceaccount.annotations }}
  annotations:
    {{- toYaml . | nindent 5 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceaccount.automount }}
{{- end }}
