apiVersion: v1
kind: Service
metadata:
  name     : {{ .Values.general.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  {{- with .Values.general.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
