apiVersion: v1
kind: Service
metadata:
  name     : {{ .Values.general.name }}-svc
  namespace: {{ .Values.general.namespace }}
spec:
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app : {{ .Values.general.labels.app }}
    bank: {{ .Values.general.labels.bank }}
    env : {{ .Values.general.labels.env }}
