#/roles/docker/tasks
- name: Install depencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add GPG Docker key
  apt_key:
    url: "{{ docker_apt_key }}"
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: Upd repo links
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-compose


