- name: systemd service
  block:
  - name: run service
    command: systemctl start {{ service_name }}
  - name: check service run status 
    service: 
      name: "{{ service_name }}"
      state: started
      enabled: true
      